### ISSUE TITLE
Can't build since update

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/meteor-scss#298]
I updated Meteor to `1.11.1` (also tried `1.12.0`) and now I can't build anymore. Dev build is still fine, `meteor reset` did no effect. The biggest problem is, that the error output is not helpful in finding the source of the error.

It stops at minification with the following error output:

```bash
While minifying app stylesheet:
<input css 22>:5185:5: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: -5px - 0 !important
^...........^
at <input css 22>:5185:5
at Object.parseError (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1200:15)
at Object.lexer_parseError (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:2333:44)
at Object.lexer_next (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3328:22)
at Object.lexer_fastLex (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3403:18)
at fastLex (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1603:27)
at Parser.parse (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1677:30)
at /home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:33:30
at walk (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:66:100)
at /home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:27:32
at container.es6:110:18
at Rule.each (container.es6:76:16)
at Rule.walk (container.es6:107:17)
at container.es6:121:24
at Root.each (container.es6:76:16)
at Root.walk (container.es6:107:17)
at /home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin (/home/username/.meteor/packages/seba_minifiers-autoprefixer/.2.0.1.12squz0.tozb++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/cssnano/dist/index.js:31:51)
at /home/username/.meteor/packages/meteor-tool/.1.11.1.1ya5b3a.s696k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
```

Now I have nowhere any `-5px - 0 !important` in my whole project nor did I change anythin in the scss files.

My build packages are

```bash
standard-minifier-js@2.6.0
fourseven:scss@4.12.0
seba:minifiers-autoprefixer@2.0.1
```

scss linter passes, too and if replacing  `seba:minifiers-autoprefixer` with `standard-minifier-css` it throws nearly the same error but with `standard-minifier-css` in the paths. I therefore assume the error to be related to this package.

**Comment by jankapunkt** [comment]
I think the compiler fails at the slightest thing. We had a fix where commented all scss and uncommented line by line until we found  a missing definition

**Comment by menewman** [comment]
Ah, that sounds painful, but... good to know! Thank you for following up 👍
